# Generated by Django 4.0.2 on 2022-03-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bank_loan_user_has_loan_finance_bank_offers_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='routing_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='credit_line',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='credit_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='debts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.IntegerField(),
        ),
    ]
