# Generated by Django 4.0.2 on 2022-04-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bank_routing_number_alter_finance_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='gender',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='race',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
    ]
